version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.3.2
  aws-cli: circleci/aws-cli@5.4.1
  tf-scripts: leecookson/tf-scripts-orb@dev:first

jobs:
  gcp-init:
    executor: gcp-cli/default
    steps:
      - checkout
      - gcp-cli/setup:
          version: 404.0.0
          use_oidc: true
      - run:
          name: Deploy step (replace with your actual logic)
          command: |
            echo "Running deployment commands...."
            gcloud iam workload-identity-pools list --location=global

  aws-init:
    executor: aws-cli/default
    steps:
      - checkout
      # run the aws-cli/setup command from the orb
      - aws-cli/setup:
          profile_name: oidc-profile
          role_arn: ${AWS_DEPLOY_IAM_ROLE}
          role_session_name: oidc-session
          session_duration: "1800"
      - run:
          name: Log-into-AWS
          command: |
            aws s3 ls --profile "OIDC-PROFILE"
  tf-plan:
    executor: gcp-cli/default
    steps:
      - checkout
      - gcp-cli/setup:
          version: 404.0.0
          use_oidc: true
      - tf-scripts/install
      - run:
          command: which tfplan;tfplan gcp
# Orchestrate our job run sequence
workflows:
  verify-gcp-oidc-access:
    jobs:
      - gcp-init
  gcp-plan:
    jobs:
      - tf-plan
  verify-aws-oidc-access:
    jobs:
      - aws-init
