name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main
    paths:
      - "aws/**"
  pull_request:
    branches:
      - main
    paths:
      - "aws/**"

# AWS_S3_BACKEND_ROLE: "arn:aws:iam::021874127869:role/s3_backend"

permissions:
  id-token: write # Required for AWS OIDC
  contents: read # Required to checkout the repo
  pull-requests: write # Required to comment on PRs with the terraform plan

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::021874127869:role/github-actions-oidc-role
          aws-region: us-east-1

      - name: Configure Terraform Backend Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::021874127869:role/s3_backend
          aws-region: us-east-1
          role-session-name: s3-backend
        run: aws sts get-caller-identity --profile s3-backend

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install TF scripts
        run: |
          git clone https://github.com/leecookson/tf-scripts.git
          chmod +x tf-scripts/bin/*
          echo "$(pwd)/tf-scripts/bin" >> $GITHUB_PATH

      - name: Terraform Plan
        id: plan
        run: tfplan aws

        continue-on-error: false
